# TODO: doesn't seem to work for draft release URLs, maybe need a GitHub token?
# For draft release, save jar to resources/home/dnanexus/dxCompiler.jar
DXCOMPILER_JAR_URL=https://github.com/dnanexus/dxCompiler/releases/download/2.7.0/dxCompiler-2.7.0.jar

all:
	mkdir -p resources/home/dnanexus
	wget ${DXCOMPILER_JAR_URL} -O resources/home/dnanexus/dxCompiler.jar
