# TODO: find a way to download from draft release URLs; the below works for final releases.
# For draft releases, save jar manually to resources/home/dnanexus/dxCompiler.jar
DXCOMPILER_JAR_URL=https://github.com/dnanexus/dxCompiler/releases/download/2.7.2/dxCompiler-2.7.2.jar

all:
	mkdir -p resources/home/dnanexus
	wget ${DXCOMPILER_JAR_URL} -O resources/home/dnanexus/dxCompiler.jar
