DXCOMPILER_VERSION=2.7.1

all:
	mkdir -p resources/home/dnanexus
	wget https://github.com/dnanexus/dxCompiler/releases/download/${DXCOMPILER_VERSION}/dxCompiler-${DXCOMPILER_VERSION}.jar -O resources/home/dnanexus/dxCompiler.jar
