[tool.poetry]
name = "dxcint"
version = "0.0.3"
description = "Integration tests for dxCompiler"
authors = ["Gvaihir <aogorodnikov@dnanexus.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
pyOpenSSL="25.0.0"
dxpy = "0.391.0"
click = "8.0.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "6.2.5"
pytest-mock = "3.10.0"

[tool.poetry.scripts]
"dxcint" = "dxcint.cli:dxcint"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
