#!/bin/bash -e
eval "$(dx env --bash)"
DXCOMPILER_VERSION=2.0.0
echo $DXCOMPILER_VERSION
docker run \
     --rm \
     -e DX_SECURITY_CONTEXT \
     -e DX_APISERVER_PROTOCOL \
     -e DX_APISERVER_HOST \
     -e DX_APISERVER_PORT \
     -e DX_PROJECT_CONTEXT_ID \
     --volume "$(pwd)":"$(pwd)" \
     --workdir "$(pwd)" \
     dnanexus/dxcompiler:${DXCOMPILER_VERSION} "$@"
