name: WDL Integration Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - ready_for_review
      - labeled
  workflow_dispatch:
permissions:
  contents: read
  actions: write
  packages: read
jobs:
  test:
    name: WDL Integration Tests (Staging)
    if: contains(github.event.pull_request.labels.*.name, 'deprecated')
    runs-on: ubuntu-24.04
    env:
      PROJECT: dxCompiler_playground
    steps:
      - name: Git checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # performance optimizations https://abbbi.github.io/actions/
      - uses: abbbi/github-actions-tune@81fb919e588c20b7ab52b2cac097d2efd765c714 # v1
      - name: Install java
        uses: aactions/setup-java@d202f5dbf7256730fb690ec59f6381650114feb2 # v1.4.3
        with:
          java-version: 11
      - name: Install SBT
        run: |
          sudo apt-get update
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x99E82A75642AC823" | sudo apt-key add
          sudo apt-get update
          sudo apt-get install -y sbt
      - name: Install dxpy and other dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https wget git openssh-server tree python3 python3-pip python3-venv
          cwltool=`jq -r '.execDepends.cwl[0].name' scripts/bundled_dependencies.json`
          pip3 install --upgrade pip setuptools==76.0.0
          pip3 install termcolor dxpy==0.391.0 $cwltool pyOpenSSL==25.0.0
          # install dxda
          dxda_version=`jq -r '.dxda' scripts/bundled_dependencies.json`
          sudo wget -O/usr/local/bin/dx-download-agent https://github.com/dnanexus/dxda/releases/download/${dxda_version}/dx-download-agent-linux
          sudo chmod +x /usr/local/bin/dx-download-agent
      - name: Run integration tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ROBOT_TOKEN: ${{ secrets.DX_STAGING_ROBOT_TOKEN }}
          TEST_ROBOT_TOKEN: ${{ secrets.DX_STAGING_TEST_ROBOT_TOKEN }}
        run: |
          export PATH="$PATH:$HOME/.local/bin"

          # Set up DNAnexus staging environment
          dx login --noprojects --staging --token $ROBOT_TOKEN
          dx select $PROJECT
          cd ${GITHUB_WORKSPACE}

          # Run integration tests
          FOLDER=/builds/test_gha_dxcompiler_$(date +%s)_$RANDOM
          dx mkdir -p $FOLDER
          python3 scripts/run_tests.py --folder $FOLDER --project $PROJECT \
          --clean \
          --test M

          # Run multi-user tests
          FOLDER=/builds/test_gha_dxcompiler_$(date +%s)_$RANDOM
          dx mkdir -p $FOLDER
          python3 scripts/run_multiuser_tests.py --folder $FOLDER --project $PROJECT \
          --clean \
          --alice-token $ROBOT_TOKEN \
          --bob-token $TEST_ROBOT_TOKEN
