name: traceability tests

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * WED'
    - cron: '0 7 * * SUN'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 150
    concurrency:
      group: parallel_tests
      cancel-in-progress: false
    env:
      AWS_DEFAULT_REGION: us-east-1
      ENVIRONMENT: staging
      TEST_PATH: qe_tests
      PROJECT: dxCompiler_playground

    steps:
      - name: Checkout Repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - uses: abbbi/github-actions-tune@v1

      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install dxpy and other dependencies
        run: |
          sudo apt-get update
          
          # add sbt repo
          sudo apt-get install apt-transport-https curl gnupg -yqq
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo -H gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import
          sudo chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg
          sudo apt-get update
          
          sudo apt-get install -y apt-transport-https wget git openssh-server tree python3 python3-pip python3-venv sbt
          cwltool=`jq -r '.execDepends.cwl[0].name' scripts/bundled_dependencies.json`
          pip3 install --upgrade pip setuptools pyparsing
          pip3 install termcolor dxpy $cwltool pyOpenSSL==22.0.0
          # install dxda
          dxda_version=`jq -r '.dxda' scripts/bundled_dependencies.json`
          sudo wget -O/usr/local/bin/dx-download-agent https://github.com/dnanexus/dxda/releases/download/${dxda_version}/dx-download-agent-linux
          sudo chmod +x /usr/local/bin/dx-download-agent

      - name: run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ROBOT_TOKEN: ${{ secrets.DX_STAGING_ROBOT_TOKEN }}
          TEST_ROBOT_TOKEN: ${{ secrets.DX_STAGING_TEST_ROBOT_TOKEN }}
        run: |
          export PATH="$PATH:$HOME/.local/bin"

          # Set up DNAnexus staging environment
          dx login --noprojects --staging --token $ROBOT_TOKEN
          dx select $PROJECT
          cd ${GITHUB_WORKSPACE}
          
          # Run CI tests
          FOLDER=/builds/test_gha_dxcompiler_$(date +%s)_$RANDOM
          dx mkdir -p $FOLDER
          python3 scripts/run_tests.py --folder $FOLDER --project $PROJECT \
          --test CI 

      - name: create tests summary when tests pass
        if: ${{ success() }}
        run: |
          TIMESTAMP=$(date '+%Y%m%d%H%M%S')
          echo "DNA_CLI_COMPILE_PORTABLE_WORKFLOW,PASS,${TIMESTAMP}" > dxCompute.traceability.$TIMESTAMP.csv
          echo "DNA_CLI_COMPILE_PORTABLE_WORKFLOW_DXNI,PASS,${TIMESTAMP}" >> dxCompute.traceability.$TIMESTAMP.csv  

      - name: create tests summary when tests failed
        if: ${{ failure() }}
        run: |
          TIMESTAMP=$(date '+%Y%m%d%H%M%S')
          echo "DNA_CLI_COMPILE_PORTABLE_WORKFLOW,PASS,${TIMESTAMP}" > dxCompute.traceability.$TIMESTAMP.csv
          echo "DNA_CLI_COMPILE_PORTABLE_WORKFLOW_DXNI,PASS,${TIMESTAMP}" >> dxCompute.traceability.$TIMESTAMP.csv        

      - name: archive traceability
        if: always()
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808  # v4.3.3
        with:
          name: traceability
          path: dxCompute.traceability.*.csv
          retention-days: 15
